title: Site Title
description: Site description
variable: site variable

collections:
  c1:
    output: true
    permalink: /:collection/:path
  c2:
    output: true
  c3:
    output: true
    permalink: /:collection/:color/:path

plugins:
  - jekyll-avatar
  - jekyll-env
  - jekyll-gist
#  - jekyll-github-metadata

gist:
  noscript: false

config_data:
  k1: first
  k2: second
  k0: third
  k5: fourth
  k4: fifth
  k3: sixth

include:
  - _pages
